### ISSUE TITLE
ERROR: the index 'ERR_SENSOR_NOT_ENABLED' does not exist

### ISSUE THREAD

**Issue by rlipscombe** [electricimp/APDS9007#12]
With the following code:

```
local lightSensor = APDS9007(lightOutputPin, 47000, lightEnablePin);

function onLightSensorRead() {
    lightSensor.read(function() {
        server.log("Light Sensor: " + value + " lux");
        imp.wakeup(10.0, onLightSensorRead);
    });
}

// we need to wait for 5 seconds before taking the first reading.
imp.wakeup(5.0, onLightSensorRead);
```

...I get the following error...

```
2017-02-14 13:47:25 UTC+0	[Device]	ERROR: the index 'ERR_SENSOR_NOT_ENABLED' does not exist
2017-02-14 13:47:25 UTC+0	[Device]	ERROR:   in read ...icimp#apds9007.class.nut#2.2.1:105
2017-02-14 13:47:25 UTC+0	[Device]	ERROR:   from onLightSensorRead device_code:15
```

**Comment by betzrhodes** [comment]
Read can be called with a callback or without a callback.  If a callback is passed in it takes one parameter result.  The code here is missing the callback parameter.  I would expect it to fail.  Where is this code taken from?  And which version of the library are you using?

lightsensor <- APDS9007(analogInputPin, RLOAD, enablePin)

lightsensor.read(function(result) {
    if ("err" in result) {
        server.log("Error Reading APDS9007: " + result.err);
    } else {
        server.log("Light level = " + result.brightness + " Lux");
    }
});

**Comment by betzrhodes** [comment]
Looking at the logs there is a bug in the library v2.2.1  - Naming mismatch for error message variables.

v2.2.1  - line 26, line 106

**Comment by rlipscombe** [comment]
> The code here is missing the callback parameter. I would expect it to fail.

It *does* fail because of that, but not until I bypass the `ERR_SENSOR_NOT_ENABLED` error by enabling the sensor.

>  Where is this code taken from?

The original example environment tail code from the Dev Center.

> And which version of the library are you using?

I'm trying to update it from 1.0.0 to 2.2.1.

**Comment by betzrhodes** [comment]
Thanks will file jiras- to fix the example code and the library.  Thanks.
